const quotes_tr = [
  { text: "En karanlık an, şafaktan hemen öncedir.", author: "Thomas Fuller" },
  { text: "Başarı, azimle kaybedilen savaşlardan sonra gelir.", author: "Winston Churchill" },
  { text: "Kendine inandığında her şey mümkündür.", author: "Audrey Hepburn" },
  { text: "Her gün yeni bir başlangıçtır.", author: "Dalai Lama" },
  { text: "Zorluklar karakteri geliştirir.", author: "James Allen" },
  { text: "Yapabileceğine inan, yolun yarısını geçtin.", author: "Theodore Roosevelt" },
  { text: "Başarı, küçük çabaların tekrarından doğar.", author: "Robert Collier" },
  { text: "Korkularını değil, umutlarını düşün.", author: "John Paul II" },
  { text: "Hayat seni yıkarsa, ayağa kalk ve devam et.", author: "Rocky Balboa" },
  { text: "Hayal edebiliyorsan, yapabilirsin.", author: "Walt Disney" },
  { text: "Başlamak, bitirmenin yarısıdır.", author: "Zig Ziglar" },
  { text: "Sabırla, her şey mümkün.", author: "Leo Tolstoy" },
  { text: "İnanç, başarıya giden ilk adımdır.", author: "Helen Keller" },
  { text: "Düşüncelerimiz hayatımızı yaratır.", author: "Marcus Aurelius" },
  { text: "Kendin ol, diğerleri zaten alınmış.", author: "Oscar Wilde" },
  { text: "Güçlükler, içindeki gücü keşfetmendir.", author: "Albert Einstein" },
  { text: "Başarı tesadüf değildir.", author: "Pele" },
  { text: "Küçük adımlar büyük yolculuklara çıkar.", author: "Confucius" },
  { text: "Hayat kısa, hayaller sonsuz.", author: "Steve Jobs" },
  { text: "Gülümse, hayat sana güler.", author: "Mother Teresa" },
  { text: "Değişim korkusuz olanların işidir.", author: "Barack Obama" },
  { text: "Düşlerin peşinden git, asla vazgeçme.", author: "Nelson Mandela" },
  { text: "Her hata yeni bir ders.", author: "Benjamin Franklin" },
  { text: "İnan ve harekete geç.", author: "Tony Robbins" },
  { text: "Mutluluk yolculuktur, varış noktası değil.", author: "Buddha" },
  { text: "Yarın bugünden başlar.", author: "Malala Yousafzai" },
  { text: "Sevgi en büyük güçtür.", author: "Martin Luther King Jr." },
  { text: "Hayatını sev, sevdiğin hayatı yaşa.", author: "Louise Hay" },
  { text: "Başarısızlık başarıya giden yoldur.", author: "Michael Jordan" },
  { text: "Cesaret korkunun üstesinden gelir.", author: "Mark Twain" },
  { text: "Her yeni gün bir fırsattır.", author: "Eleanor Roosevelt" },
  { text: "Zorluklar seni güçlendirir.", author: "Friedrich Nietzsche" },
  { text: "Hayallerin peşinden git.", author: "Walt Disney" },
  { text: "Kendine güven, her şey oradan başlar.", author: "Diane von Fürstenberg" },
  { text: "Başarı azimle gelir.", author: "Vince Lombardi" },
  { text: "Hayat, cesur olanları ödüllendirir.", author: "Helen Keller" },
  { text: "Pozitif düşün, pozitif yaşa.", author: "Norman Vincent Peale" },
  { text: "İnandığın sürece asla kaybetmezsin.", author: "Muhammed Ali" },
  { text: "Hayatını değiştir, dünyayı değiştir.", author: "Mahatma Gandhi" },
  { text: "Başarı, küçük alışkanlıkların sonucudur.", author: "Aristoteles" },
  { text: "Hedefsiz gemiye hiçbir rüzgar yardım etmez.", author: "Seneca" },
  { text: "Kendin ol, en iyi versiyonun ol.", author: "Ralph Waldo Emerson" },
  { text: "Sabırla ve inançla ilerle.", author: "Confucius" },
  { text: "Hayatın anlamı sevgidir.", author: "Leo Buscaglia" },
  { text: "Hayat seninle başlar.", author: "John Wooden" },
  { text: "Başarı, devam eden çabadır.", author: "Elbert Hubbard" },
  { text: "Kendini sev, dünyayı sev.", author: "Buddha" },
  { text: "Her gün yeni bir umut taşır.", author: "Anne Frank" },
  { text: "İnanç, mümkün olanı mümkün kılar.", author: "Norman Vincent Peale" },
];

const quotes_en = [
  { text: "The darkest hour is just before the dawn.", author: "Thomas Fuller" },
  { text: "Success is not final, failure is not fatal.", author: "Winston Churchill" },
  { text: "Believe you can and you're halfway there.", author: "Theodore Roosevelt" },
  { text: "Every day is a new beginning.", author: "Dalai Lama" },
  { text: "Difficulties strengthen the mind.", author: "James Allen" },
  { text: "Start where you are. Use what you have.", author: "Arthur Ashe" },
  { text: "It always seems impossible until it's done.", author: "Nelson Mandela" },
  { text: "Your limitation—it's only your imagination.", author: "Unknown" },
  { text: "Push yourself, because no one else is going to do it for you.", author: "Unknown" },
  { text: "Dream it. Wish it. Do it.", author: "Unknown" },
  { text: "Success is the sum of small efforts repeated.", author: "Robert Collier" },
  { text: "Fear is a reaction. Courage is a decision.", author: "Winston Churchill" },
  { text: "Do what you can with all you have.", author: "Theodore Roosevelt" },
  { text: "Dream big and dare to fail.", author: "Norman Vaughan" },
  { text: "Keep going. Be all in.", author: "Bryan Hutchinson" },
  { text: "Stay positive, work hard, make it happen.", author: "Unknown" },
  { text: "Success doesn't just find you. You have to go out and get it.", author: "Unknown" },
  { text: "Great things never come from comfort zones.", author: "Unknown" },
  { text: "Push yourself, because no one else will do it for you.", author: "Unknown" },
  { text: "Don't stop when you're tired. Stop when you're done.", author: "Unknown" },
  { text: "The harder you work for something, the greater you'll feel when you achieve it.", author: "Unknown" },
  { text: "Dream bigger. Do bigger.", author: "Unknown" },
  { text: "Wake up with determination. Go to bed with satisfaction.", author: "Unknown" },
  { text: "Little things make big days.", author: "Unknown" },
  { text: "It's going to be hard, but hard does not mean impossible.", author: "Unknown" },
  { text: "Don't wait for opportunity. Create it.", author: "Unknown" },
  { text: "Sometimes we're tested not to show our weaknesses, but to discover our strengths.", author: "Unknown" },
  { text: "The key to success is to focus on goals, not obstacles.", author: "Unknown" },
  { text: "You don't have to be perfect to be amazing.", author: "Unknown" },
  { text: "Don't watch the clock; do what it does. Keep going.", author: "Sam Levenson" },
  { text: "Success is the best revenge.", author: "Kanye West" },
  { text: "The best way to predict the future is to create it.", author: "Peter Drucker" },
  { text: "Your attitude determines your direction.", author: "Unknown" },
  { text: "Believe in yourself and all that you are.", author: "Christian D. Larson" },
  { text: "Don't quit. Suffer now and live the rest of your life as a champion.", author: "Muhammad Ali" },
  { text: "You are capable of amazing things.", author: "Unknown" },
  { text: "Success usually comes to those who are too busy to be looking for it.", author: "Henry David Thoreau" },
  { text: "Opportunities don't happen, you create them.", author: "Chris Grosser" },
  { text: "Don't be afraid to give up the good to go for the great.", author: "John D. Rockefeller" },
  { text: "I find that the harder I work, the more luck I seem to have.", author: "Thomas Jefferson" },
  { text: "The way to get started is to quit talking and begin doing.", author: "Walt Disney" },
  { text: "Success is not how high you have climbed, but how you make a positive difference to the world.", author: "Roy T. Bennett" },
  { text: "Try not to become a man of success, but rather try to become a man of value.", author: "Albert Einstein" },
  { text: "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.", author: "Roy T. Bennett" },
  { text: "Believe in the possibility of what you can be.", author: "Unknown" },
  { text: "Everything you can imagine is real.", author: "Pablo Picasso" },
  { text: "Act as if what you do makes a difference. It does.", author: "William James" },
  { text: "What you get by achieving your goals is not as important as what you become by achieving your goals.", author: "Zig Ziglar" },
];

const getQuotesByLanguage = (language) => {
  return language === 'tr' ? quotes_tr : quotes_en;
};

export default getQuotesByLanguage;
